### PR TITLE
Addition of quality to acestream listings

### PR DESCRIPTION
**Pull request by jackyaz**

### CODE REVIEW

**Comment by TheCannings** [comment]
Hey, so someone on the addons4kodi reddit asked to add quality to the listings, so I hacked something together, feel free to disregard :) nice work on the original

**Comment by jackyaz** [comment]
That would be me ;-) Requested a merge so iwannabelikemike can consider combining it into his plugin. May need to restrict the changes to just /r/soccerstreams, I'm not sure if all subreddits follow the quality link publishing rules they use. If I understood Python a little better (I've made a couple of addons, but nothing major!) I'd try myself!

**Comment by TheCannings** [comment]
Yeah it really rough and assumes that the link is published the same way of quality and stream name then link

**Comment by jackyaz** [comment]
I've taken the lazy way out for now, and edited the subreddits list to just soccerstreams since that's all I'm after!

Did look through rest of code but wasn't sure where I could make the quality conditional.

**Comment by TheCannings** [comment]
I've added a bit to clip the end of the acestream link if you want to resubmit the pr

**Comment by jackyaz** [comment]
Not 100% sure how to resubmit, I think it picks it up cos it wants to merge the 2 master branches anyway?

**Comment by jackyaz** [comment]
P.S. that edit seems to break in Kodi, invalid syntax

SyntaxError: ('invalid syntax', ('C:\\Users\\Jack\\AppData\\Roaming\\Kodi\\addons\\plugin.video.sparkle\\resources\\lib\\modules\\subreddits2.py', 46, 39, "                        if findstr[0] = '':\n"))

**Comment by jackyaz** [comment]
Annoyingly :(

https://www.reddit.com/r/soccerstreams/comments/7wd4ao/must_read_rules_updated_for_all_streamers/
https://i.imgur.com/OzITykQ.png


Am I right in thinking I can just move the quality code from findstring[0] to [1]?

**Comment by jackyaz** [comment]
`import os
import log_utils
import re
import urlparse
import praw2
import xbmc

CLIENT_ID = 'J_0zNv7dXM1n3Q'
CLIENT_SECRET = 'sfiPkzKDd8LZl3Ie1WLAvpCICH4'
USER_AGENT = 'sparkle streams 1.0'

class subreddits(object):
    as_regex_str = r'(acestream://[^$\s]+)'
    newregex = r'(.*acestream://.*)'
    comment_url = 'https://www.reddit.com/r/MMAStreams/comments/{}'

    def __init__(self, username=None, password=None):
        self.client = praw2.Reddit(client_id=CLIENT_ID,
                              client_secret=CLIENT_SECRET,
                              user_agent=USER_AGENT,
                              username=username,
                              password=password,
                            )
        self.as_regex = re.compile(self.as_regex_str, re.IGNORECASE)

    def events(self, subreddit, filtering=False):
        subs = []
        path = '/r/{}'.format(subreddit)
        for submission in self.client.get(path):
            sub_id = submission.id
            score = submission.score
            title = submission.title
            title = title.encode('utf-8')
            subs.append({'submission_id': sub_id, 'title': title, 'score': score })
        return sorted(subs, key=lambda d: d['score'], reverse=True)

    def event_links(self, submission_id):
        submission = self.client.submission(id=submission_id)
        links = []
        for c in submission.comments.list():
            if hasattr(c, 'body'):
                linkline = re.findall(self.newregex, c.body.encode('utf-8'))
                if linkline:
                    for x in range(0, len(linkline)):
                        findstr = linkline[x].split('acestream://')
                        endlink = findstr[1].find(' ')
                        if endlink <= 0:
                            findstr.append('No Quality Found')
                        if endlink > 0:
                            findstr.append(findstr[1][endlink:])
                            findstr[1] = findstr[1][:endlink]
                        links.append({'quality': re.sub('[^A-Za-z0-9 ]', '', findstr[2]).strip(),
                                      'comment_id': c.id,
                                      'score': c.score,
                                      'ace_links': findstr[1]})
        # Return the list sorted by score
        return sorted(links, key=lambda d: d['score'], reverse=True)`

**Pull request closed without merging**
